version: '3.9'

services: 
  backend:
    build: ./example-backend
    restart: unless-stopped
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASE=postgres
    ports: 
      - 8080:8080
    depends_on: 
      - db
    
  frontend:
    build: ./example-frontend
    restart: unless-stopped
    ports: 
      - 5000:5000

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  db:
    image: postgres:13.4-alpine
    restart: unless-stopped
    environment: 
      POSTGRES_PASSWORD: secret
    container_name: postgres_db
    volumes: 
      - database:/var/lib/postgresql/data
    
volumes:
  database:

