version: '3.9'

services: 
  backend:
    build: ./example-backend
    restart: unless-stopped
    environment: 
      - REDIS_HOST=redis
    ports: 
      - 8080:8080
    
  frontend:
    build: ./example-frontend
    restart: unless-stopped
    ports: 
      - 5000:5000

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379